---
- hosts: all
  become: true
  vars_files:
    - ansible-vars.yml
  remote_user: "{{ username }}"
  vars:
    kubeadm_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

  tasks:
    - name: Reset kubeadm
      command: /usr/bin/kubeadm reset
      async: 45
      poll: 0      
      ignore_errors: true

    - name: Remove packages
      apt:
        name: '{{ kubeadm_packages | list }}'
        state: absent
        update_cache: true
      ignore_errors: true
      when: ansible_distribution == 'Ubuntu'      

    - name: Remove kubernetes repository (apt)
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent
      when: ansible_distribution == 'Ubuntu'

    - name: Update apt cache
      apt:
        update_cache: true    

    - name: Remove kubernetes directorys
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/kubernetes
        - /run/kubernetes
        - ~/.kube
        - /var/lib/etcd
      ignore_errors: true
    - name: reboot
      reboot:
        reboot_timeout: 180 #allow 3 minutes for reboot to happen